version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test
    volumes:
      - db-data:/var/lib/postgresql/data
  nb:
      build: .
      command: ["./main"]
      restart: always
      ports:
        - "8080:8080"
      networks:
        - web_app
      depends_on:
        - db
networks:
  web_app:
    driver: bridge
volumes:
  db-data:
    driver: local